name: CI Pipeline 

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-lint-docker: 
    runs-on: ubuntu-latest

    steps:
      -name: Checkout code
       uses: actions/checkout@v3
    
      -name: Say pipeline is running
       run: echo "Pipeline is running"
  
      -name: Set up Pyhton 
       uses: actions/setup-python@v4
       with:
         python-version: "3.10"
         
      -name: Install Independecies
       run: pip install -r requirements.txt
  
      -name: Run tests
       run: pytest
  
      -name: lint with flake8
       run: |
         pip install flake8
         flale8 .
  
      -name: Build Docker image
       run: docker build -t devops-app:latest
      


  
